---

ansible_connection: ansible.netcommon.network_cli
ansible_network_cli_ssh_type: libssh
ansible_network_os: community.routeros.routeros
ansible_user: admin
ansible_password: "{{ lookup('bws_cache', 'switch-password').value }}"

mt_uplink: ether1

mt_bridges:
  - name: bridge
    # frame-types: admit-only-vlan-tagged
    ingress-filtering: false
    vlan-filtering: true
    auto-mac: false
    admin-mac: "{{ ansible_net_interfaces.ether1['mac-address'] }}"

mt_addresses:
  - address: 10.52.10.4/24
    interface: vlan10

mt_vlan_interfaces:
  - name: vlan10
    comment: Infrastructure
    vlan-id: 10
    interface: "{{ mt_bridges[0].name }}"

mt_bridge_ports:
  - bridge: "{{ mt_bridges[0].name }}"
    interface: "{{ mt_uplink }}"
    comment: brs-sw01 uplink
    tagged: [10, 15, 20, 25, 30]

  - bridge: "{{ mt_bridges[0].name }}"
    interface: ether2
    comment: desk mac
    untagged: 20

  - bridge: "{{ mt_bridges[0].name }}"
    interface: ether3
    comment: brs-ap03
    tagged: [10, 20, 25, 30]

  - bridge: "{{ mt_bridges[0].name }}"
    interface: ether4
    comment: esx2
    tagged: [10, 15]

  - bridge: "{{ mt_bridges[0].name }}"
    interface: ether5
    comment: ugreen-nas-1
    untagged: 10

  - bridge: "{{ mt_bridges[0].name }}"
    interface: ether6
    comment: ugreen-nas-2
    untagged: 10

  - bridge: "{{ mt_bridges[0].name }}"
    interface: ether9
    comment: pikvm
    untagged: 10

  - bridge: "{{ mt_bridges[0].name }}"
    interface: ether10
    comment: brs-ups01
    untagged: 10

  - bridge: "{{ mt_bridges[0].name }}"
    interface: ether24
    comment: adhoc guest
    untagged: 25

mt_bridge_vlans: >-
  {{ sitedata[site_short].subnets | map('ansible.utils.keep_keys', ['name', 'vlan_id'])
    | map('combine', {'bridge': mt_bridges[0].name})
  }}

mt_bridge_vlan_extra_interfaces:
  - bridge: "{{ mt_bridges[0].name }}"
    vlan_id: 10
    interface: "{{ mt_bridges[0].name }}"
    type: tagged
