---
- name: Check pool exists
  community.general.zpool_facts:
    name: "{{ zfs_pool.name }}"
  register: zpool_info
  failed_when: "'msg' in zpool_info and not 'does not exist' in zpool_info.msg"

- name: Try and import ZFS pool
  ansible.builtin.command:
    cmd: "zpool import -f {{ zfs_pool.name }}"
  register: command_result
  when: "'msg' in zpool_info"
  changed_when: "command_result.rc == 0 and command_result.stdout == '' and command_result.stderr == ''"
  failed_when: not 'no such pool available' in command_result.stderr and command_result.rc

- name: Create zfs pool
  ansible.builtin.include_tasks:
    file: create_pool.yml
  when: "not command_result.changed and 'msg' in zpool_info"
