update_netbox: true

network_spec:
  vpn:
    mgmt_vpn: 10.0.20.0/24
    jens_vpn: 10.0.21.0/24

  vlan:
    default:
      vlan_id: 1
    # routable nets
    mgmt:
      vlan_id: 10
      network: 10.0.1.0/24
    network_mgmt:
      vlan_id: 20
      network: 10.0.2.0/24
    lan:
      vlan_id: 30
      network: 10.0.3.0/24
    dmz:
      vlan_id: 40
      network: 10.0.4.0/24
    wlan:
      vlan_id: 50
      network: 10.0.5.0/24
    guest_wlan:
      vlan_id: 60
      network: 10.0.6.0/24
    vm_network:
      vlan_id: 70
      network: 10.0.7.0/24

    # private nets
    esxi_storage:
      vlan_id: 200
      network: 10.2.1.0/24
    esxi_migration:
      vlan_id: 210
      network: 10.2.2.0/24
    vm_storage:
      vlan_id: 220
      network: 10.2.3.0/24

    # transits
    ir_transit:
      vlan_id: 400
      network: 10.1.2.0/24

    fw_cluster_pfsync:
      vlan_id: 420
      network: 10.1.4.0/24

    wan_vlan:
      vlan: 1000
