all:
  children:
    packer_templates:
      children:
        debian_templates:
          hosts:
            nas-template:
            deb-x12-template:

    storage:
      children:
        nas:
    networking:
      hosts:
        netbox:
      children:
        routing:
          children:
            core_fw_cu:
            gw_fw_cu:
        switches:
          hosts:
            rack-switch-stack:
            indoor-switch:
    services:
      children:
        jankvisor_services:
        dns:
        docker_hosts:
          children:
            docker_gpu_hosts:
            networking_services:
    proxmox:
    debian:
      hosts:
        nas-template:
        deb-x12-template:
    opnsense:
