plugin: community.general.proxmox
url: https://10.0.1.30:8006/
user: ansible@pam
token_id: ansible-inventory
token_secret: "{{ lookup('bws_cache', 'proxmox-ansible-inventory-token').value }}"

validate_certs: false  # only do this when you trust the network!
exclude_nodes: true
want_facts: true
keyed_groups:
    # proxmox_tags_parsed is an example of a fact only returned when 'want_facts=true'
  - key: proxmox_tags_parsed | default("all")
    separator: ""
compose:
  ansible_host: >-
    proxmox_agent_interfaces
    | default([])
    | map(attribute="ip-addresses")
    | flatten
    | ansible.utils.reduce_on_network('10.0.1.0/24')
    | first
    | default("")
    | ansible.utils.ipaddr("address")
strict: true
