nmcli_interfaces:
  - name: ens192
    method: manual
    gateway: "10.0.7.1"
    dns: "10.0.7.1"
    ip: 10.0.7.21/24

  - name: ens256
    method: manual
    ip: 10.2.3.11/24

deploy_docker_roles:
  - languagetool
  - nginx_ping
  - prometheus

deploy_docker_services:
  - taskin

deploy_docker_roles:
  - nginx_ping
