configure_switch_vlans:
  - name: mgmt
    tagged_ports:
      - 1/1/2
      - 1/3/1
      - 1/1/10
    untagged_ports:
      - 1/1/23 to 1/1/24
  - name: lan
    tagged_ports:
      - 1/1/2
      - 1/3/1
    untagged_ports:
      - 1/1/3
  - name: wlan
    tagged_ports:
      - 1/1/10
      - 1/3/1
    untagged_ports:
      - 1/3/2

configure_switch_native_vlan:
  - interface: 1/1/10
    native_vlan: mgmt

configure_switch_netconfig: "{{ network_spec }}"

ansible_network_os: community.network.icx
ansible_connection: ansible.netcommon.network_cli
ansible_become: true
ansible_become_method: enable
ansible_host: 10.0.1.5

ansible_user: root
ansible_password: "{{ lookup('bws_cache', 'ripple_user_password').value }}"
