nmcli_interfaces:
  - name: ens192
    method: manual
    gateway: "10.0.6.1"
    dns: "10.0.6.1"
    ip: 10.0.6.10/24

deploy_docker_services:
  - net_stack
  - technisync

deploy_docker_roles:
  - unifi_controller
