configure_switch_interfaces:
  mgmt_port:
    interface: ether1
    comment: MGMT_uplink

  esxi_storage2_uplink:
    interface: sfp-sfpplus1
    comment: esxi_storage2

  esxi_storage1_uplink:
    interface: sfp-sfpplus2
    comment: esxi_storage2

  windows_uplink:
    interface: sfp-sfpplus3
    comment: windows_desktop

  jankvisor_uplink:
    interface: sfp-sfpplus4
    comment: jankvisor_desktop



configure_switch_bridges:
  main_bridge:
    interface: bridgeLocal
    vlan_filtering: true
    admin_mac: 74:4D:28:E3:3E:B9
    ports:
      - interface: mgmt_port
        untagged: mgmt
      - interface: esxi_storage2_uplink
        tagged:
          - mgmt
          - network_mgmt
          - lan
          - dmz
          - wlan
          - guest_wlan
          - vm_network
          - esxi_storage
          - esxi_migration
          - vm_storage
          - ir_transit
          - fw_cluster_pfsync
      - interface: esxi_storage1_uplink
        tagged:
          - mgmt
          - network_mgmt
          - lan
          - dmz
          - wlan
          - guest_wlan
          - vm_network
          - esxi_storage
          - esxi_migration
          - vm_storage
          - ir_transit
          - fw_cluster_pfsync

      - interface: windows_uplink
        untagged: lan
      - interface: jankvisor_uplink
        tagged:
          - lan
          - mgmt
          - network_mgmt

configure_switch_vlan_interfaces:
  mgmt_interface:
    bridge: main_bridge
    vlan: network_mgmt
    address: 10.0.2.5/24


configure_switch_type: mikrotik

ansible_connection: ansible.netcommon.network_cli
ansible_network_cli_ssh_type: libssh
ansible_network_os: community.routeros.routeros

ansible_become: true
ansible_become_method: enable
ansible_host: 10.0.2.5

ansible_user: admin
ansible_password: "{{ lookup('bws_cache', 'ripple_user_password').value }}"

