---
- name: Restart the dnsmasq container
  community.general.docker_container:
    name: dns
    image: strm/dnsmasq
    restart_policy: always
    state: started
    restart: true
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /etc/dnsmasq.conf:/etc/dnsmasq.conf
    capabilities:
      - NET_ADMIN
