---
- name: Install nmcli
  ansible.builtin.include_tasks:
    file: install.yml

- name: Configure nmcli interfaces
  ansible.builtin.include_tasks:
    file: configure_interface.yml
  loop: "{{ nmcli_interfaces }}"
  loop_control:
    loop_var: "nmcli_interface"
