internal_domain: int.ripplefcl.com

port_mapping:
  network_mgmt: vmx0
  routing_trunk: vmx1



configure_opnsense_general_settings:
  dnsserver: "10.0.7.10"
  dnsserver: "10.0.7.11"
  timezone: Europe/London

configure_opnsense_packages:
  - os-ddclient
  - os-theme-cicada
