

configure_opnsense_rules:
  - interface: "mgmt_vpn"
    rule_blocks:
      - "allow_mgmt_vpn"
    local_rule_blocks:
      allow_mgmt_vpn:
        - description: allow all mgmt vpn traffic
          action: pass

  - interface: mgmt
    rule_blocks:
      - "allow_dhcp"
      - "allow_dns"
      - "allow_internet"
      - "allow_icmp"
      - "block_all"

  - interface: "fw_cluster_pfsync"
    rule_blocks:
      - "allow_all"
    local_rule_blocks:
      allow_all:
        - description: "allow all"
          action: "pass"

  - interface: "lan"
    rule_blocks:
      - "allow_to_jens"
      - "allow_dhcp"
      - "allow_dns"
      - "allow_internet"
      - "allow_media"
      - "allow_services"
      - "allow_mgmt_vpn"
      - "block_all"


  - interface: "guest_lan"
    rule_blocks:
      - "allow_dhcp"
      - "allow_dns"
      - "allow_internet"
      - "block_all"

  - interface: "vm_network"
    rule_blocks:
      - "allow_to_jens"
      - "allow_dhcp"
      - "allow_icmp"
      - "allow_dns"
      - "allow_internet"
      - "allow_dnet_net"
      - "block_all"
      - "allow_prom_scrape"
    local_rule_blocks:
      allow_prom_scrape:
        - description: allow prom_scape to bws_cache-proxy
          action: pass
          protocol: "TCP"
          destination:
            port: 5000

  - interface: "jens_link"
    rule_blocks:
      - "allow_icmp"
      - "allow_jens"
      - "block_all"

    local_rule_blocks:
      allow_jens:
        - description: allow vpn traffic
          action: "pass"
          source:
            network: self

        - description: "allow it mate jens"
          action: "pass"
          source:
            alias: jens_ip_space

  - interface: bt_wan
    rule_blocks:
      # - "block_private_out"
      - "allow_icmp"
      - "block_all"

    local_rule_blocks:
      block_private_out:
        - description: "allow double nat outer network"
          direction: out
          action: "pass"
          source:
            alias: private_ips
          destination:
            network: 192.168.1.0/24
        - description: "allow double nat network"
          direction: out
          action: "pass"
          source:
            network: 192.168.1.0/24
          destination:
            alias: private_ips
            invert: true
        - description: "block private ips"
          log: true
          direction: "out"
          action: "block"
          source:
            alias: private_ips

