
configure_opnsense_interfaces:
  network_mgmt:
    identifier: lan
    vlan: network_mgmt
    config:
      if: "{{ port_mapping.network_mgmt }}"

  bt_wan:
    identifier: opt1
    vlan: wan_vlan
    config:
      subnet: "24"
      blockbogons: "1"

  mgmt:
    identifier: opt2
    vlan: mgmt

  lan:
    identifier: opt3
    vlan: lan

  guest_lan:
    identifier: opt4
    vlan: guest_lan

  vm_network:
    identifier: opt5
    vlan: vm_network

  fw_cluster_pfsync:
    identifier: opt6
    vlan: fw_cluster_pfsync

  mgmt_vpn:
    identifier: opt7
    config:
      if: wg0

  jens_link:
    identifier: opt8
    config:
      if: wg1

  "WireGuard (Group)":
    identifier: wireguard
    config:
      internal_dynamic: "1"
      if: "wireguard"
      virtual: "1"
      type: "group"
      networks: ""

  Loopback:
    identifier: lo0
    config:
      internal_dynamic: "1"
      enable: "1"
      type: none
      virtual: "1"
      if: lo0
      ipaddr: "127.0.0.1"
      subnet: "8"
      ipaddrv6: "::1"
      subnetv6: "128"
