
configure_opnsense_interfaces:
  network_mgmt:
    identifier: lan
    vlan: network_mgmt
    config:
      if: "{{ port_mapping.network_mgmt }}"

  mgmt:
    identifier: opt9
    vlan: mgmt
    config:
      if: "{{ port_mapping.mgmt }}"

  lan:
    identifier: opt1
    vlan: lan

  wlan:
    identifier: opt2
    vlan: wlan
    config:
      if: "{{ port_mapping.wifi }}"

  guest_wlan:
    identifier: opt3
    vlan: guest_wlan
    config:
      if: "{{ port_mapping.guest_wifi }}"

  ir_transit:
    identifier: opt4
    vlan: ir_transit

  fw_cluster_pfsync:
    identifier: opt5
    vlan: fw_cluster_pfsync

  vm_network:
    identifier: opt6
    vlan: vm_network

  mgmt_vpn:
    identifier: opt7
    config:
      if: wg0

  jens_link:
    identifier: opt8
    config:
      if: wg1

  "WireGuard (Group)":
    identifier: wireguard
    config:
      internal_dynamic: "1"
      if: "wireguard"
      virtual: "1"
      type: "group"
      networks: ""

  Loopback:
    identifier: lo0
    config:
      internal_dynamic: "1"
      enable: "1"
      type: none
      virtual: "1"
      if: lo0
      ipaddr: "127.0.0.1"
      subnet: "8"
      ipaddrv6: "::1"
      subnetv6: "128"
