
configure_opnsense_vip:
  - interface: "bt_wan"
    vlan: wan_vlan
    description: lan carp
    vhid: 1
    password: test
    mode: "carp"
    address: "192.168.1.10/24"
  - interface: "lan"
    vlan: lan
    description: lan carp
    vhid: 2
    password: test
    mode: "carp"
    address: "10.0.3.1/24"
  - interface: "guest_lan"
    vlan: guest_lan
    description: guest_lan carp
    vhid: 4
    password: test
    mode: "carp"
    address: "10.0.6.1/24"
  - interface: "vm_network"
    vlan: vm_network
    description: vm_network carp
    vhid: 5
    password: test
    mode: "carp"
    address: "10.0.7.1/24"
  - interface: "mgmt"
    vlan: mgmt
    description: mgmt carp
    vhid: 6
    password: test
    mode: "carp"
    address: "10.0.1.1/24"
