---
- name: Create app directory
  ansible.builtin.file:
    path: "{{ prometheus_base_path }}/data"
    owner: "ripple"
    group: "ripple"
    mode: '0755'
    state: directory

- name: Template Prometheus config
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_base_path }}/prometheus.yml"
    owner: "ripple"
    group: "ripple"
    mode: '0664'
  notify: restart prometheus


- name: Template Prometheus web config
  ansible.builtin.template:
    src: prometheus-web.yml.j2
    dest: "{{ prometheus_base_path }}/web.yml"
    owner: "ripple"
    group: "ripple"
    mode: '0664'
  notify: restart prometheus

- name: Create docker stack
  community.docker.docker_compose_v2:
    project_name: 'prometheus'
    definition: '{{ prometheus_service_def }}'
