---
- name: Configure bridges
  community.routeros.api_modify:
    path: interface bridge
    data: "{{ query('tikify', 'bridges')  }}"
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible
  tags: ["interfaces", "bridge"]

- name: Configure VLAN interfaces
  community.routeros.api_modify:
    path: interface vlan
    data: "{{ query('tikify', 'vlans') }}"
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible
  tags: ["interfaces", "vlan"]

- name: Configure addresses
  community.routeros.api_modify:
    path: ip address
    data: "{{ query('tikify', 'addresses') }}"
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible
  tags: ["interfaces", "address"]

- name: Configure bridge port(s)
  community.routeros.api_modify:
    path: interface bridge port
    data: "{{ query('tikify', 'bridge_ports') }}"
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible
  tags: ["interfaces", "bridge"]

- name: Configure bridge VLANs
  community.routeros.api_modify:
    path: interface bridge vlan
    data: "{{ query('tikify', 'bridge_vlans') }}"
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible
  tags: ["interfaces", "bridge"]

