---

- name: Gather RouterOS facts
  community.routeros.api_facts:

- name: Include system
  ansible.builtin.include_tasks:
    file: system.yml
    apply:
      tags: system
  tags: system

- name: Include interfaces
  ansible.builtin.include_tasks:
    file: interfaces.yml
    apply:
      tags: interfaces
  tags: interfaces
