---

- name: Set hostname
  community.routeros.api_modify:
    path: system identity
    data: [name: "{{ inventory_hostname }}"]
    handle_absent_entries: remove
    handle_entries_content: remove_as_much_as_possible

- name: Set login banner
  community.routeros.api_modify:
    path: system note
    data: "{{ [item] }}"
  loop:
    - note: "\
        \n      ----------------------------------------\
        \n      |\
        \n      | Arch melt Detected, faggy login to: {{ inventory_hostname }}\
        \n      |\
        \n      ----------------------------------------"
    - show-at-login: true
  loop_control:
    label: "{{ item | dict2items | map(attribute='key') | first }}"
