- name: Setup Dhcp relay
  community.general.xml:
    path: /conf/config.xml
    xpath: /opnsense/OPNsense/DHCRelay
    set_children: "{{  configure_opnsense_dhcp_relay | dhcprelay2xml(configure_opnsense_interfaces) }}"
    pretty_print: true
  notify: Reboot opnsense router
