- name: "Create expected folders"
  file:
    state: directory
    path: "{{ item }}"
    mode: '0775'
    owner: 'root'
    group: '101'
  loop:
    - "{{ kea_container_base_dir }}"
    - "{{ kea_container_base_dir }}/config"
    - "{{ kea_container_base_dir }}/leases"
    - "{{ kea_container_base_dir }}/logs"
    - "{{ kea_container_base_dir }}/sockets"
    - "{{ kea_container_base_dir }}/entrypoint.d"

- name: "Copy Kea DHCP configuration files"
  template:
    src: "{{ item }}"
    dest: "{{ kea_container_base_dir }}/config/{{ item | regex_replace('.j2', '') }}"
    owner: "root"
    group: "101"
    mode: "0664"
  loop:
    - "dhcp4.json.j2"
    - "subnet.json.j2"
  register: kea_config

- name: "Start Kea DHCP4 container"
  docker_container:
    name: "kea-dhcp4"
    image: "jonasal/kea-dhcp4:2"
    pull: yes
    state: started
    restart_policy: always
    command: "-c /kea/config/dhcp4.json"
    volumes:
      - "{{ kea_container_base_dir }}/config:/kea/config:ro"
      - "{{ kea_container_base_dir }}/leases:/kea/leases"
      - "{{ kea_container_base_dir }}/logs:/kea/logs"
      - "{{ kea_container_base_dir }}/sockets:/kea/sockets"
      - "{{ kea_container_base_dir }}/entrypoint.d:/entrypoint.d:ro"
    network_mode: host
    purge_networks: true
  notify: Create dhcp container
